// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcError } from "./RpcError";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * host -> core response to a [`Request`].
 */
export type Response = { id: string, ok: boolean, result?: JsonValue | null, error?: RpcError | null, };
